org: taotao
app: serverless
service: serverless
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  app:
    handler: controllers/itemController.getAllCategory
    events: 
      - http: 
          path: /item/getItem
          method: GET
          cors: true